name: Azure Pipelines
variables:
  python.version: '3.7.6'
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Hosted Ubuntu 1604
    steps:
    # Needed for Terraform VM deployment
     - task: InstallSSHKey@0
       inputs:
        knownHostsEntry: 'github.com'
        sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDTWSZpXKSrja9mACA0+j+0fp0VQHgNQvEq4Ta0DTJLV+XYyrcPjWS3gr5a2I2eYn2FFKZg/x+yOk0BshcB+jRqYEqMviq+yyvKa6vcwNR8E1T0nbaPRGV3SvuMI6c5pom5z1T1Ol1qACvM7V5ngrjUpGD2eEAgmTJ+TRdzkLZoHCwxRHm6uj7/0UdfEithiLcGWlmtJq1igsnmFgoCwYkdM+dQDaiAS8amoVMWL0sQxYKxtjwFmShdsnnhvWEAs1MjmMecat74yxNBEmPS91k5O0trPuS4rRmuMbYCr/q5qvpcwT15fTJO08JQRZy1lvE3U7oHpBAI8tHJwthD+yk8YdP1EmOl85oXnPutmrhGm4OPUAwRsl5CUarc3rNXPjYGNnRwgvjjb0Ujc5uMWeqsZIdXPgzSlGxZQgcwqLpYvTopPcmen7qx6I5k/M1J7BXdGwWJ+dtE//OnwHoMSnY8Qt2pP1I0wMAdCximNZ/gXxIniU1NmU3qM9vccDz8+uPZKiKSuwLAbHeeyXPu8xUEQ/2ry5CtzV7TnBgj8wBDZjT7rPUrWHJTnIIGatJE2proXNja48fVwGcrhp3D6aV8iW+BWyz5cE63RNhcMJ+LRLs2gHUaaCQAnhyPKwLWRXGDPxtvCloTb/+XHOAH6AuPEGMB3LpwiOqbXlnokeirDw== devops21a@outlook.com'
        sshKeySecureFile: 'id_rsa'
     - task: ArchiveFiles@2
       displayName: 'Archive FakeRestAPI'
       inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/fakerestapi'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
     - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
       displayName: 'Upload Package'
       artifact: drop-fakerestapi
     - task: CopyFiles@2
       inputs: 
            SourceFolder: '$(Build.SourcesDirectory)'
            Contents: 'selenium/*' 
            TargetFolder: $(Build.ArtifactStagingDirectory)
     - task: PublishBuildArtifacts@1
       inputs:
            PathtoPublish: $(Build.ArtifactStagingDirectory)
            ArtifactName: LoginTestSuite 
- stage:
  jobs:
  - deployment: FakeRestAPI
    pool:
      vmImage: 'Ubuntu-16.04'
    environment: 'TEST'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: 'Free Trial (ff63d938-3ec1-4bbb-a80e-2f733dd33cf6)'
              appName: 'web-app-proj-qr'
              appType: webApp
              package: $(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip
  - job: JMeter
    pool: 
      vmImage: 'Ubuntu-16.04'
    steps:
     - task: JMeterInstaller@0
       displayName: 'Install JMeter 5.3'
       inputs:
         jmeterVersion: '5.3'
     - task: Bash@3
       displayName: 'Run JMeter test' 
       inputs:
        targetType: inline
        script: |
          jmeter -n -t JMeter/Starter.jmx -l JMeter/result.jtl
  - deployment: VMDeploy
    displayName: NAME
    environment: 
      name: lastenv
      resourceType: VirtualMachine
      tags: web
    strategy:
       runOnce:
        deploy:
         steps:
         - task: Bash@3
           inputs:
            targetType: inline 
            script: |
                 #!/bin/bash
                 sudo apt-get upgrade -y
                 sudo apt-get install python3-pip -y
                 sudo apt-get install unzip -y
                 sudo apt-get install -y chromium-browser
                 pip3 install selenium
         


