resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: vs2017-win2016
  steps:
  - checkout: self
  - task: DownloadBuildArtifacts@0
    displayName: Download Artifacts
    inputs:
      buildType: specific
      project: fd1bd439-c841-4b31-b347-28f630694097
      definition: 9
      artifactName: LoginTestSuite
  - task: CopyFiles@2
    displayName: 'Copy Files to: D:\a\1\a\LoginTestSuite\selenium\bin'
    inputs:
      SourceFolder: D:\a\1\a\LoginTestSuite\selenium
      TargetFolder: D:\a\1\a\LoginTestSuite\selenium\bin
      CleanTargetFolder: true
      OverWrite: true
  - task: CmdLine@2
    displayName: Install Selenium-webdriver
    inputs:
      script: >
        npm install selenium-webdriver
      workingDirectory: D:\a\1\a\LoginTestSuite\selenium\bin
  - task: CmdLine@2
    displayName: Install chromedriver
    inputs:
      script: >
        npm install chromedriver
      workingDirectory: D:\a\1\a\LoginTestSuite\selenium\bin
  - task: PythonScript@0
    displayName: Run login.py
    inputs:
      scriptPath: D:\a\1\a\LoginTestSuite\selenium\bin\login.py
...
